Endurraða Lögunum og laga auka space í Lögum um aðalfund mgr. 2
NORDhi/nord-log pull request #3
Opened 2023-04-04 14:22 UTC by Gunnarbjo

Stjórn Nörd hefur heimild til að breyta uppröðun laga hvenær sem er. Stjórn hefur einnig heimild til að lagfæra augljósar stafsetningar- og innsláttarvillur hvenær sem er, án þess að þurfa samþykki félaga. Tilkynna skal allar slíkar breytingar opinberlega fyrir félögum Nörd. Berist kvörtun yfir einhverri breytingu innan viku frá tilkynningunni skal viðkomandi málsgrein þegar færð í fyrra horf.

2023-04-04 14:30 UTC, ofurtumi commented
Finnst óþarfi að linka í málsgreinar ef þær hafa engin nöfn, fínt að hafa þar sem málsgreinar hafa undirtitla en 
- [7. gr. Lög um aðild að félaginu](#7-gr-lög-um-aðild-að-félaginu)
  - [1. mgr.](#1-mgr-6)
  - [2. mgr.](#2-mgr-3)
  - [3. mgr.](#3-mgr)
  - [4. mgr.](#4-mgr)
  - [5. mgr.](#5-mgr)

segir mér ekkert rosa mikið

2023-04-04 14:32 UTC, Gunnarbjo commented
Ástæðan fyrir því er að það er lagabreyting að koma frá mér þar sem þessar málsgreinar fá lýsingar, geri mér grein fyrir að það er ljótt eins og er en það verður bót fyrir því, þarf samt aðalfund til þess að setja nöfnin

2023-04-04 14:34 UTC, ofurtumi commented
En er þá ekki nóg að hafa bara yfirlit greina þangað til

2023-04-04 14:36 UTC, ofurtumi requested changes
Fjarlægja linka á málsgreinar, ef þær koma inn seinna með nöfnum þá er það bara guddy

2023-04-11 20:31 UTC, ofurtumi approved these changes
gud SHIT, á ég að mergea?

2023-04-11 20:43 UTC, merged